project:
  type: website

website:
  title: "Vogelnotities"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: tellen.qmd
        text: Tellen
      - href: identificatie.qmd
        text: Identificatie
  
  sidebar:
    - title: "Telprojecten"
      style: "docked"
      contents:
        - text: "Telprojecten"
          file: tellen.qmd
        - text: "BMP tellingen"
          file: telprojecten/bmp/bmp.qmd
        - text: "Wintervogeltelling"
          file: telprojecten/watervogels/watervogels.qmd
        - text: "Slaapplaatstelling kiekendieven"
          file: telprojecten/slaapplaats/slaapplaats_kieken.qmd
        
    - title: "Identificatie"
      contents:
        - text: "Identificatie"
          file: identificatie.qmd
        - text: "Meeuwen"
          file: soortgroepen/meeuwen/meeuwen.qmd
        - text: "Piepers"
          file: soortgroepen/piepers/piepers.qmd
        - text: "Kiekendieven"
          file: soortgroepen/kiekendieven/kiekendieven.qmd
        - text: "Ganzen"
          file: soortgroepen/ganzen/ganzen.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


